### ISSUE TITLE
Support for SCTP checksum update

### ISSUE THREAD

**Issue by loxi-admin** [loxilb-io/loxilb-ebpf#3]
After SCTP NAT loxilb can't update checksum due to no proper way to update sctp checksum in eBPF. We need to be able to support it. (Current workaround is simply to disable sctp checksum at sctp hosts which is not a viable solution)

**Comment by dj-nlx** [comment]
With the  commit 37f162a, we can now support sctp checksum natively in loxilb ebpf.
